var symbol = [{ symbol: "KCA" },
    { symbol: "VBK" },
    { symbol: "QHD" },
    { symbol: "MVG" },
    { symbol: "QEF" },
    { symbol: "ZMA" },
    { symbol: "SMF" },
    { symbol: "UOJ" },
    { symbol: "RWO" },
    { symbol: "EMQ" },
    { symbol: "ASJ" },
    { symbol: "MAG" },
    { symbol: "YHN" },
    { symbol: "MVX" },
    { symbol: "OWT" },
    { symbol: "IMC" },
    { symbol: "BFT" },
    { symbol: "ZJP" },
    { symbol: "GFJ" },
    { symbol: "DCU" },
    { symbol: "TTE" },
    { symbol: "NVE" },
    { symbol: "QJP" },
    { symbol: "QTJ" },
    { symbol: "SEF" },
    { symbol: "OFJ" },
    { symbol: "AQR" },
    { symbol: "ASU" },
    { symbol: "HER" },
    { symbol: "RRS" },
    { symbol: "GFB" },
    { symbol: "AYM" },
    { symbol: "MOG" },
    { symbol: "HHH" },
    { symbol: "SMR" },
    { symbol: "PET" },
    { symbol: "VOC" },
    { symbol: "EBZ" },
    { symbol: "OOG" },
    { symbol: "UPO" },
    { symbol: "LUF" },
    { symbol: "IYU" },
    { symbol: "OHV" },
    { symbol: "CRC" },
    { symbol: "QWN" },
    { symbol: "DPG" },
    { symbol: "SGG" },
    { symbol: "VNH" },
    { symbol: "NWQ" },
    { symbol: "ZEC" },
    { symbol: "FGO" },
    { symbol: "AMP" },
    { symbol: "SUO" },
    { symbol: "ZYP" },
    { symbol: "VKE" },
    { symbol: "QHM" },
    { symbol: "QCX" },
    { symbol: "QPE" },
    { symbol: "RTE" },
    { symbol: "KAK" },
    { symbol: "ILB" },
    { symbol: "MFA" },
    { symbol: "UOV" },
    { symbol: "LJQ" },
    { symbol: "LII" },
    { symbol: "HKZ" },
    { symbol: "MXG" },
    { symbol: "NVM" },
    { symbol: "BTG" },
    { symbol: "XFQ" },
    { symbol: "ELI" },
    { symbol: "ZPZ" },
    { symbol: "MTU" },
    { symbol: "KXN" },
    { symbol: "FOR" },
    { symbol: "NJC" },
    { symbol: "LRU" },
    { symbol: "UEH" },
    { symbol: "YHU" },
    { symbol: "XVC" },
    { symbol: "IZV" },
    { symbol: "LWB" },
    { symbol: "QBA" },
    { symbol: "EPO" },
    { symbol: "CYN" },
    { symbol: "RGF" },
    { symbol: "UEK" },
    { symbol: "UNM" },
    { symbol: "BAW" },
    { symbol: "SLN" },
    { symbol: "XZA" },
    { symbol: "GIU" },
    { symbol: "MMS" },
    { symbol: "TWV" },
    { symbol: "NSR" },
    { symbol: "ENL" },
    { symbol: "GZM" },
    { symbol: "PKA" },
    { symbol: "EOV" },
    { symbol: "PDJ" }
];

var released_date = [
    { released_date: "2002-03-11" },
    { released_date: "2003-07-04" },
    { released_date: "2004-05-31" },
    { released_date: "2006-03-01" },
    { released_date: "2006-06-09" },
    { released_date: "2006-12-11" },
    { released_date: "2006-12-29" },
    { released_date: "2007-05-03" },
    { released_date: "2007-05-08" },
    { released_date: "2008-02-12" },
    { released_date: "2009-07-21" },
    { released_date: "2009-11-19" },
    { released_date: "2011-11-04" },
    { released_date: "2012-12-14" },
    { released_date: "2013-02-12" },
    { released_date: "2013-05-13" },
    { released_date: "2015-01-05" },
    { released_date: "2015-01-09" },
    { released_date: "2016-02-12" },
    { released_date: "2016-05-04" },
    { released_date: "2016-08-31" },
    { released_date: "2017-01-24" },
    { released_date: "2017-05-09" },
    { released_date: "2019-03-12" },
    { released_date: "2019-04-02" },
    { released_date: "2002-03-07" },
    { released_date: "2002-11-27" },
    { released_date: "2003-08-22" },
    { released_date: "2005-02-15" },
    { released_date: "2005-09-26" },
    { released_date: "2006-05-15" },
    { released_date: "2006-08-04" },
    { released_date: "2006-12-26" },
    { released_date: "2007-08-21" },
    { released_date: "2007-10-29" },
    { released_date: "2007-11-01" },
    { released_date: "2007-11-15" },
    { released_date: "2007-12-31" },
    { released_date: "2008-05-29" },
    { released_date: "2008-06-16" },
    { released_date: "2009-04-22" },
    { released_date: "2009-05-27" },
    { released_date: "2010-03-10" },
    { released_date: "2010-08-11" },
    { released_date: "2013-03-15" },
    { released_date: "2013-09-17" },
    { released_date: "2016-09-01" },
    { released_date: "2017-03-09" },
    { released_date: "2017-05-15" },
    { released_date: "2016-02-17" },
    { released_date: "2016-04-14" },
    { released_date: "2016-05-10" },
    { released_date: "2016-05-26" },
    { released_date: "2016-07-11" },
    { released_date: "2016-11-21" },
    { released_date: "2016-11-22" },
    { released_date: "2017-01-30" },
    { released_date: "2017-02-15" },
    { released_date: "2017-08-02" },
    { released_date: "2018-02-09" },
    { released_date: "2018-04-04" },
    { released_date: "2018-05-08" },
    { released_date: "2018-08-21" },
    { released_date: "2018-08-30" },
    { released_date: "2018-09-10" },
    { released_date: "2018-11-09" },
    { released_date: "2018-12-17" },
    { released_date: "2019-05-17" },
    { released_date: "2019-10-17" },
    { released_date: "2019-03-21" },
    { released_date: "2005-06-14" },
    { released_date: "2005-08-01" },
    { released_date: "2001-06-14" },
    { released_date: "2002-07-08" },
    { released_date: "2002-08-15" },
    { released_date: "2002-11-27" },
    { released_date: "2004-10-14" },
    { released_date: "2005-03-28" },
    { released_date: "2005-05-13" },
    { released_date: "2005-06-14" },
    { released_date: "2005-08-01" },
    { released_date: "2005-11-16" },
    { released_date: "2006-06-22" },
    { released_date: "2006-07-14" },
    { released_date: "2008-02-14" },
    { released_date: "2008-09-18" },
    { released_date: "2010-07-27" },
    { released_date: "2010-08-16" },
    { released_date: "2013-02-06" },
    { released_date: "2015-12-09" },
    { released_date: "2017-01-16" },
    { released_date: "2017-07-03" },
    { released_date: "2018-10-02" },
    { released_date: "2019-06-07" },
    { released_date: "2019-06-20" },
    { released_date: "2019-12-05" },
    { released_date: "2016-11-18" },
    { released_date: "2017-03-17" },
    { released_date: "2018-02-23" },
    { released_date: "2019-03-20" }
];

var name = [
    { "name": "Walmart" },
    { "name": "Exxon Mobil" },
    { "name": "Berkshire Hathaway" },
    { "name": "Apple" },
    { "name": "UnitedHealth Group" },
    { "name": "McKesson" },
    { "name": "CVS Health" },
    { "name": "Amazon.com" },
    { "name": "AT&T" },
    { "name": "General Motors" },
    { "name": "Ford Motor" },
    { "name": "AmerisourceBergen" },
    { "name": "Chevron" },
    { "name": "Cardinal Health" },
    { "name": "Costco" },
    { "name": "Verizon" },
    { "name": "Kroger" },
    { "name": "General Electric" },
    { "name": "Walgreens Boots Alliance" },
    { "name": "JPMorgan Chase" },
    { "name": "Fannie Mae" },
    { "name": "Alphabet" },
    { "name": "Home Depot" },
    { "name": "Bank of America Corp." },
    { "name": "Express Scripts Holding" },
    { "name": "Wells Fargo" },
    { "name": "Boeing" },
    { "name": "Phillips 66" },
    { "name": "Anthem" },
    { "name": "Microsoft" },
    { "name": "Valero Energy" },
    { "name": "Citigroup" },
    { "name": "Comcast" },
    { "name": "IBM" },
    { "name": "Dell Technologies" },
    { "name": "State Farm Insurance Cos." },
    { "name": "Johnson & Johnson" },
    { "name": "Freddie Mac" },
    { "name": "Target" },
    { "name": "Lowes" },
    { "name": "Marathon Petroleum" },
    { "name": "Procter & Gamble" },
    { "name": "MetLife" },
    { "name": "UPS" },
    { "name": "PepsiCo" },
    { "name": "Intel" },
    { "name": "DowDuPont" },
    { "name": "Archer Daniels Midland" },
    { "name": "Aetna" },
    { "name": "FedEx" },
    { "name": "United Technologies" },
    { "name": "Prudential Financial" },
    { "name": "Albertsons Cos." },
    { "name": "Sysco" },
    { "name": "Disney" },
    { "name": "Humana" },
    { "name": "Pfizer" },
    { "name": "HP" },
    { "name": "Lockheed Martin" },
    { "name": "AIG" },
    { "name": "Centene" },
    { "name": "Cisco Systems" },
    { "name": "HCA Healthcare" },
    { "name": "Energy Transfer Equity" },
    { "name": "Caterpillar" },
    { "name": "Nationwide" },
    { "name": "Morgan Stanley" },
    { "name": "Liberty Mutual Insurance Group" },
    { "name": "New York Life Insurance" },
    { "name": "Goldman Sachs Group" },
    { "name": "American Airlines Group" },
    { "name": "Best Buy" },
    { "name": "Cigna" },
    { "name": "Charter Communications" },
    { "name": "Delta Air Lines" },
    { "name": "Facebook" },
    { "name": "Honeywell International" },
    { "name": "Merck" },
    { "name": "Allstate" },
    { "name": "Tyson Foods" },
    { "name": "United Continental Holdings" },
    { "name": "Oracle" },
    { "name": "Tech Data" },
    { "name": "TIAA" },
    { "name": "TJX" },
    { "name": "American Express" },
    { "name": "Coca-Cola" },
    { "name": "Publix Super Markets" },
    { "name": "Nike" },
    { "name": "Andeavor" },
    { "name": "World Fuel Services" },
    { "name": "Exelon" },
    { "name": "Mass Mutual Life Insurance" },
    { "name": "Rite Aid" },
    { "name": "ConocoPhillips" },
    { "name": "CHS" },
    { "name": "3M" },
    { "name": "Time Warner" },
    { "name": "General Dynamics" },
    { "name": "USAA" }
];

var total = [
    { "total": "151" },
    { "total": "3036" },
    { "total": "6482" },
    { "total": "1996" },
    { "total": "178" },
    { "total": "6340" },
    { "total": "2284" },
    { "total": "2495" },
    { "total": "9065" },
    { "total": "1571" },
    { "total": "4806" },
    { "total": "1752" },
    { "total": "1755" },
    { "total": "2300" },
    { "total": "8675" },
    { "total": "2398" },
    { "total": "1721" },
    { "total": "3437" },
    { "total": "27" },
    { "total": "2836" },
    { "total": "6666" },
    { "total": "8749" },
    { "total": "1986" },
    { "total": "3670" },
    { "total": "9759" },
    { "total": "1589" },
    { "total": "7895" },
    { "total": "3781" },
    { "total": "637" },
    { "total": "4505" },
    { "total": "8437" },
    { "total": "7149" },
    { "total": "8596" },
    { "total": "8290" },
    { "total": "9749" },
    { "total": "4800" },
    { "total": "2980" },
    { "total": "5756" },
    { "total": "1882" },
    { "total": "69" },
    { "total": "3715" },
    { "total": "2812" },
    { "total": "7397" },
    { "total": "939" },
    { "total": "6249" },
    { "total": "8013" },
    { "total": "8716" },
    { "total": "8004" },
    { "total": "4077" },
    { "total": "5061" },
    { "total": "5093" },
    { "total": "6786" },
    { "total": "1689" },
    { "total": "352" },
    { "total": "9869" },
    { "total": "6459" },
    { "total": "2693" },
    { "total": "7733" },
    { "total": "89" },
    { "total": "2065" },
    { "total": "6525" },
    { "total": "5931" },
    { "total": "2057" },
    { "total": "436" },
    { "total": "1389" },
    { "total": "8431" },
    { "total": "5575" },
    { "total": "8349" },
    { "total": "2215" },
    { "total": "3744" },
    { "total": "4932" },
    { "total": "4165" },
    { "total": "3697" },
    { "total": "6639" },
    { "total": "206" },
    { "total": "7461" },
    { "total": "7478" },
    { "total": "4639" },
    { "total": "5710" },
    { "total": "8900" },
    { "total": "6520" },
    { "total": "6970" },
    { "total": "1445" },
    { "total": "4773" },
    { "total": "946" },
    { "total": "7721" },
    { "total": "3722" },
    { "total": "7785" },
    { "total": "8897" },
    { "total": "8082" },
    { "total": "2541" },
    { "total": "6528" },
    { "total": "25" },
    { "total": "1189" },
    { "total": "2260" },
    { "total": "6588" },
    { "total": "5099" },
    { "total": "8268" },
    { "total": "86,77" },
    { "total": "97" }
];

var country = [
    { "country": "Russia" },
    { "country": "China" },
    { "country": "China" },
    { "country": "USA" },
    { "country": "India" },
    { "country": "USA" },
    { "country": "Russia" },
    { "country": "Russia" },
    { "country": "Russia" },
    { "country": "USA" },
    { "country": "USA" },
    { "country": "USA" },
    { "country": "USA" },
    { "country": "USA" },
    { "country": "Russia" },
    { "country": "India" },
    { "country": "India" },
    { "country": "Russia" },
    { "country": "India" },
    { "country": "China" },
    { "country": "Russia" },
    { "country": "China" },
    { "country": "China" },
    { "country": "India" },
    { "country": "Russia" },
    { "country": "USA" },
    { "country": "India" },
    { "country": "China" },
    { "country": "USA" },
    { "country": "India" },
    { "country": "China" },
    { "country": "USA" },
    { "country": "Russia" },
    { "country": "Russia" },
    { "country": "China" },
    { "country": "India" },
    { "country": "Russia" },
    { "country": "USA" },
    { "country": "Russia" },
    { "country": "USA" },
    { "country": "China" },
    { "country": "USA" },
    { "country": "USA" },
    { "country": "China" },
    { "country": "Russia" },
    { "country": "USA" },
    { "country": "India" },
    { "country": "China" },
    { "country": "Russia" },
    { "country": "USA" },
    { "country": "Russia" },
    { "country": "India" },
    { "country": "China" },
    { "country": "Russia" },
    { "country": "China" },
    { "country": "Russia" },
    { "country": "India" },
    { "country": "India" },
    { "country": "Russia" },
    { "country": "USA" },
    { "country": "USA" },
    { "country": "USA" },
    { "country": "Russia" },
    { "country": "USA" },
    { "country": "China" },
    { "country": "USA" },
    { "country": "India" },
    { "country": "India" },
    { "country": "India" },
    { "country": "Russia" },
    { "country": "Russia" },
    { "country": "USA" },
    { "country": "USA" },
    { "country": "India" },
    { "country": "USA" },
    { "country": "Russia" },
    { "country": "USA" },
    { "country": "Russia" },
    { "country": "Russia" },
    { "country": "Russia" },
    { "country": "Russia" },
    { "country": "China" },
    { "country": "Russia" },
    { "country": "India" },
    { "country": "Russia" },
    { "country": "USA" },
    { "country": "USA" },
    { "country": "USA" },
    { "country": "USA" },
    { "country": "Russia" },
    { "country": "USA" },
    { "country": "USA" },
    { "country": "USA" },
    { "country": "USA" },
    { "country": "India" },
    { "country": "USA" },
    { "country": "India" },
    { "country": "India" },
    { "country": "Russia" },
    { "country": "India" }
];

var price = [
    { "price": "458" },
    { "price": "659" },
    { "price": "825" },
    { "price": "809" },
    { "price": "75" },
    { "price": "928" },
    { "price": "527" },
    { "price": "284" },
    { "price": "215" },
    { "price": "881" },
    { "price": "346" },
    { "price": "550" },
    { "price": "694" },
    { "price": "894" },
    { "price": "466" },
    { "price": "943" },
    { "price": "764" },
    { "price": "429" },
    { "price": "602" },
    { "price": "994" },
    { "price": "56" },
    { "price": "793" },
    { "price": "753" },
    { "price": "986" },
    { "price": "326" },
    { "price": "52" },
    { "price": "438" },
    { "price": "925" },
    { "price": "556" },
    { "price": "367" },
    { "price": "135" },
    { "price": "933" },
    { "price": "827" },
    { "price": "676" },
    { "price": "371" },
    { "price": "18" },
    { "price": "713" },
    { "price": "59" },
    { "price": "850" },
    { "price": "43" },
    { "price": "98" },
    { "price": "129" },
    { "price": "118" },
    { "price": "144" },
    { "price": "216" },
    { "price": "361" },
    { "price": "508" },
    { "price": "792" },
    { "price": "419" },
    { "price": "210" },
    { "price": "670" },
    { "price": "161" },
    { "price": "199" },
    { "price": "356" },
    { "price": "907" },
    { "price": "647" },
    { "price": "963" },
    { "price": "567" },
    { "price": "295" },
    { "price": "21" },
    { "price": "732" },
    { "price": "806" },
    { "price": "252" },
    { "price": "277" },
    { "price": "479" },
    { "price": "551" },
    { "price": "760" },
    { "price": "585" },
    { "price": "647" },
    { "price": "644" },
    { "price": "993" },
    { "price": "267" },
    { "price": "399" },
    { "price": "749" },
    { "price": "669" },
    { "price": "769" },
    { "price": "675" },
    { "price": "292" },
    { "price": "305" },
    { "price": "525" },
    { "price": "509" },
    { "price": "145" },
    { "price": "376" },
    { "price": "6" },
    { "price": "886" },
    { "price": "280" },
    { "price": "634" },
    { "price": "156" },
    { "price": "595" },
    { "price": "683" },
    { "price": "231" },
    { "price": "237" },
    { "price": "351" },
    { "price": "969" },
    { "price": "176" },
    { "price": "256" },
    { "price": "365" },
    { "price": "297" },
    { "price": "6" },
    { "price": "50" }
];

stockArray = [];
fjson = { stock: [] }
for (var i = 0; i < 100; i++) {
    var stock1 = {
        "symbol": symbol[i].symbol,
        "released_date": released_date[i].released_date,
        "price": (price[i].price * 0.1).toFixed(2),
        "company": {
            "name": name[i].name,
            "total": total[i].total,
            "country": (country[i].country).toUpperCase()
        }
    }
    stockArray.push(stock1);
}
var temp = { stock: stockArray };
var fjson = { stocks: temp };
console.log(JSON.stringify(fjson));